### PR TITLE
Set up a "Hello world" Back End project with RoR

### PR DESCRIPTION
**Pull request by Kidd254**
In this pull request I:
- [ ]     Created a new Rails API app called 'hello-rails-back-end'.
- [ ]     Initialized my project with Git.
- [ ]     Made sure that my project has a Postgres database set up.
- [ ]     Created a table for storing my messages and create 5 different greetings.
- [ ]     Created an API endpoint that selects a random greeting from my table.

### CODE REVIEW

**Comment by binhussen** [comment]
@Kidd254 would you update the front readme file and add the backend URL on it

**Comment by Kidd254** [comment]
Ok...I thought I did...let me check

**Comment by Kidd254** [comment]
@binhussen the links are already in the readme

**Comment by binhussen** [comment]
@Kidd254 I don't mean this repository readme file, update the [front-end repository](https://github.com/Kidd254/Hello_react_front_end) readme file and add the this URL to it.

**Comment by Kidd254** [comment]
@binhussen  I understand

**Review by binhussen — APPROVED** [review]
Hi @Kidd254 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
IApproveSimonCowellGIF (6)

## Highlights
- Setuped Rails-React app ✔️
- Well Stractured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kidd254** [comment]
@binhussen thanks for your patience.. I have made the change

**Pull request merged**
